### ISSUE TITLE
`bundler exec rake spec` failes with undefined method `shared_context_metadata_behavior='

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#1062]
I had pulled the latest yard source from github. Ran `bundler install` and then tried to run `bundler exec rake spec`, but I'm getting errors in return. 

## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. Clone repo
2. Run `bundler install`
3. Run `bundler exec rake spec`

## Actual Output

```
C:\Users\tthomas2\SourceTree\yard (master)
λ bundle exec rake spec
C:/Ruby23/bin/ruby.exe -I'C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib';'C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib' 'C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb'
C:/Users/tthomas2/SourceTree/yard/spec/spec_helper.rb:159:in `block in <top (required)>': undefined method `shared_context_metadata_behavior=' for #<RSpec::Core::Configuration:0x310fab8> (NoMethodError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core.rb:97:in `configure'
        from C:/Users/tthomas2/SourceTree/yard/spec/spec_helper.rb:119:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
C:/Ruby23/bin/ruby.exe -I'C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib';'C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib' 'C:/Ruby23/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb' failed
```

## Expected Output

Expected the RSpec tests to run successfully.

## Environment details:

* OS: Windows 10
* Ruby version (`ruby -v`): ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
* YARD version (`yard -v`): [Enter output of `yard -v`]
* Relevant software dependency/versions:
  * Bundler version 1.13.7

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by thomthom** [comment]
So it turns out after I had ran `bundle install`, and then I checked `bundle exec rspec -v` it returned 3.4.4.

Now looking at the source of RSpec it turns out that `Configuration.shared_context_metadata_behavior` was added first in 3.5. So `spechelper.rb` failed at line 159.

After going into `Gemfile` and changing the rspec line to: `gem 'rspec', '~> 3.5'` and then ran `bundle install` again then `bundle exec rake spec` finally worked.
