### ISSUE TITLE
cannot parse `if` statement in `Array` element

### ISSUE THREAD

**Issue by hiro4bbh** [lsegal/yard#1066]
I found a bug that yardoc cannot parse `if` statement in `Array` element.

## Steps to reproduce
I think the following is the minimal code for reproducing the problem:

```ruby
# test.rb
i, j = 1, 2
if j then
  [if i == 0 then false else true end, 0]
else
  [if i == 0 then false else true end, 1]
end
```

## Actual Output
The following is actual output:

```
$ yardoc doc --debug test.rb
[debug]: Parsing ["doc", "test.rb"] with `ruby` parser
[debug]: Parsing test.rb
[warn]: Cannot parse `test.rb': bad value for range
[warn]: ArgumentError: bad value for range
[warn]: Stack trace:
	/usr/local/lib/ruby/gems/2.4.0/gems/yard-0.9.8/lib/yard/parser/ruby/ruby_parser.rb:235:in `initialize'
	/usr/local/lib/ruby/gems/2.4.0/gems/yard-0.9.8/lib/yard/parser/ruby/ruby_parser.rb:235:in `new'
	/usr/local/lib/ruby/gems/2.4.0/gems/yard-0.9.8/lib/yard/parser/ruby/ruby_parser.rb:235:in `visit_event'
	/usr/local/lib/ruby/gems/2.4.0/gems/yard-0.9.8/lib/yard/parser/ruby/ruby_parser.rb:165:in `on_if'
	/usr/local/lib/ruby/gems/2.4.0/gems/yard-0.9.8/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/usr/local/lib/ruby/gems/2.4.0/gems/yard-0.9.8/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'

[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
[debug]: Generating asset js/jquery.js
[debug]: Serializing to doc/js/jquery.js
[debug]: Generating asset js/app.js
[debug]: Serializing to doc/js/app.js
[debug]: Generating asset js/full_list.js
[debug]: Serializing to doc/js/full_list.js
[debug]: Generating asset css/style.css
[debug]: Serializing to doc/css/style.css
[debug]: Generating asset css/common.css
[debug]: Serializing to doc/css/common.css
[debug]: Generating asset css/full_list.css
[debug]: Serializing to doc/css/full_list.css
[debug]: Generating asset class_list.html
[debug]: Serializing to doc/class_list.html
[debug]: Generating asset method_list.html
[debug]: Serializing to doc/method_list.html
[debug]: Generating asset file_list.html
[debug]: Serializing to doc/file_list.html
[debug]: Generating asset frames.html
[debug]: Serializing to doc/frames.html
[debug]: Serializing to doc/index.html
[debug]: Serializing to doc/_index.html
[debug]: Serializing to doc/top-level-namespace.html
Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

## Expected Output

I have no expected output, only let yard parse this code.

## Environment details:

* OS: macOS Sierra version 10.12.2
* Ruby version (`ruby -v`): ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
* YARD version (`yard -v`): yard 0.9.8
* Relevant software dependency/versions: none

I have read the Contributing Guide.

**Comment by lsegal** [comment]
Closing out some old issues. Given the significant age of this, it would be best to re-open with new context if it's still relevant.
