### ISSUE TITLE
Yard not working on Ruby 1.9.3

### ISSUE THREAD

**Issue by jessebs** [lsegal/yard#1089]
## Steps to reproduce
1. Run the following command: `yard -v` on Ruby 1.9.3

## Actual Output
jbowes@jbowes-mac ~/projects/nai-utils$ yard doc --no-private --debug
/Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/lib/yard/globals.rb:21:in `log': /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/lib/yard/logging.rb:13: invalid multibyte char (US-ASCII) (SyntaxError)
/Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/lib/yard/logging.rb:13: invalid multibyte char (US-ASCII)
/Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/lib/yard/logging.rb:13: syntax error, unexpected $end, expecting keyword_end
    PROGRESS_INDICATORS = %w(⣷ ⣯ ⣟ ⡿ ⢿ ⣻ ⣽ ⣾)
                               ^
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/lib/yard/cli/command_parser.rb:57:in `initialize'
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/lib/yard/cli/command_parser.rb:54:in `new'
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/lib/yard/cli/command_parser.rb:54:in `run'
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/gems/yard-0.9.9/bin/yard:13:in `<top (required)>'
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/bin/yard:23:in `load'
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/bin/yard:23:in `<main>'
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jbowes/.rvm/gems/ruby-1.9.3-p551@nai-utils/bin/ruby_executable_hooks:15:in `<main>'

## Expected Output
Expect yard to work

## Environment details:

* OS: CentOS 7 and MacOS 10.12.4
* Ruby version (`ruby -v`): ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin16.0.0]
* YARD version (`yard -v`): 0.9.9

## Fix
In lib/yard/logging.rb, the encoding line must be the first line

**Comment by zverok** [comment]
0_0 Somebody still uses 1.9.3 in production?..

**Comment by jessebs** [comment]
The contrib guide specifies "Ruby versions (1.8+)"

**Comment by zverok** [comment]
Yes, I understand your concern (I am not a contributor, unforturnately, just interested spectator). Of course, all explictily specified Ruby versions **should** be supported. I am just wondering whether there are still real cases for 1.9 support except for abandoned gems docs.

**Comment by lsegal** [comment]
This is easy enough to fix.

**Comment by jessebs** [comment]
You can go ahead and close Pull Request 1090 since you fixed it.

**Comment by lsegal** [comment]
YARD's policy on 1.8 was defined in [v0.9.6](https://github.com/lsegal/yard/blob/master/CHANGELOG.md#096---january-7th-2017), by the way:

> Removed official support for Ruby 1.x (1.8/1.9). YARD can still be installed in these versions, but support is not guaranteed. Simple bug fixes may still be considered via pull request only. Issues without code will be automatically closed.
