### ISSUE TITLE
Yardoc tries to read directory named readme

### ISSUE THREAD

**Issue by BurdetteLamar** [lsegal/yard#1160]
When I have a directory named readme in my main project directory, yardoc fails.

## Steps to reproduce

1. Create directory ./readme.
2. Run yardoc.
3. See error message.

Here are my files/dirs in the project (top level):

$ ls -1
bin/
CODE_OF_CONDUCT.md
Gemfile
Gemfile.lock
images/
lib/
LICENSE
LICENSE.txt
markdown_helper.gemspec
MarkdownHelper/
pkg/
Rakefile
**readme/**
README.md
test/

## Actual Output

```$ yardoc --debug
C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/lib/yard/code_objects/extra_file_object.rb:77:in `read': Is a directory @ rb_sysopen - readme (Errno::EISDIR)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/lib/yard/code_objects/extra_file_object.rb:77:in `ensure_parsed'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/lib/yard/code_objects/extra_file_object.rb:25:in `initialize'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/lib/yard/cli/yardoc.rb:299:in `new'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/lib/yard/cli/yardoc.rb:299:in `parse_arguments'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/lib/yard/cli/yardoc.rb:248:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/lib/yard/cli/command.rb:14:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/yard-0.9.12/bin/yardoc:13:in `<top (required)>'
        from C:/Ruby22/bin/yardoc:23:in `load'
        from C:/Ruby22/bin/yardoc:23:in `<main>'
```

## Expected Output

No errors

## Environment details:

* OS: OS Name	Microsoft Windows 7 Home Premium Version	6.1.7601 Service Pack 1 Build 7601
* Ruby version (`ruby -v`): ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]
* YARD version (`yard -v`): yard 0.9.12

## Fwiw

Why, you may ask, would I have a directory named readme?  Because my README.md file is built from a number of source files, most of which live in that directory.  If interested, see gem [markdown_helper](https://rubygems.org/gems/markdown_helper).

**Comment by lsegal** [comment]
My guess is YARD is picking up `readme` as the first `README*` file in your directory. You can work around this by telling YARD where your readme is with 

```
yard --readme README.md
```

Or by placing `--readme README.md` in your `.yardopts` file.

**Comment by BurdetteLamar** [comment]
Or, as in my case, renaming to readme_files.

**Comment by SolaWing** [comment]
if the readme dictory is other's gem, we can't modify it.

a simple patch 
```
        readme = Dir.glob('README{,*[^~]}').
          select { |fn| File.file? fn }. # this line
          sort_by {|r| [r.count('.'), r.index('.'), r] }.first
```
fix the problem

**Comment by lsegal** [comment]
> [!NOTE]
> This is a batch message, apologies if this feels impersonal.

I am closing out a few stale issues and PRs in the YARD repo and this was flagged for automatic closure because the issue may have been fixed or is likely not planned due to the issue/PR age. If this is still an issue or you believe the issue/PR is still worth a discussion, please feel free to comment or reopen a new issue. Thanks and sorry for not getting around to this the first time!
