### ISSUE TITLE
Uninitialized constant RDoc::Markup::BlockQuote

### ISSUE THREAD

**Issue by saurabhnanda** [lsegal/yard#1183]
Running `bundle exec yard doc` crashes with an error (given below), whereas `bundle exec rdoc` works absolutely fine.

## Steps to reproduce

This is for a private repo, so, steps aren't really relevant.

## Actual Output

```
bundle exec yard doc --debug
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp}"] with `ruby` parser
[debug]: Parsing lib/sms_job.rb
[debug]: Parsing lib/email_job.rb
[debug]: Missing object Admin in file `app/controllers/admin/tags_controller.rb', moving it to the back of the line.

... lot of similar output ...

[warn]: Syntax error in `lib/generators/translation_model_for/templates/translated_model.rb`:(1,8): syntax error, unexpected '<'
[warn]: ParserSyntaxError: syntax error in `lib/generators/translation_model_for/templates/translated_model.rb`:(1,8): syntax error, unexpected '<'
[warn]: Stack trace:
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:583:in `on_parse_error'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:442:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:46:in `block in parse'

[debug]: Parsing lib/generators/translation_model_for/templates/translations_model.rb
[warn]: Syntax error in `lib/generators/translation_model_for/templates/translations_model.rb`:(1,8): syntax error, unexpected '<'
[warn]: ParserSyntaxError: syntax error in `lib/generators/translation_model_for/templates/translations_model.rb`:(1,8): syntax error, unexpected '<'
[warn]: Stack trace:
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:583:in `on_parse_error'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:442:in `parse'
  /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/parser/source_parser.rb:46:in `block in parse'

[debug]: Parsing filename1_redacted.rb
[debug]: Re-processing filename2_redacted.rb...
[debug]: Missing object ActiveAdmin in file `filename3_redacted.rb', moving it to the back of the line.

... lot of similar output ...

[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
[debug]: Re-generating object Class1Redacted...
[debug]: Re-generating object Class2Redacted...
[debug]: Re-generating object Class3Redacted...

... lot of similar output ...

[debug]: Generating asset js/jquery.js
[debug]: Serializing to doc/js/jquery.js
[debug]: Generating asset js/app.js
[debug]: Serializing to doc/js/app.js
[debug]: Generating asset js/full_list.js
[debug]: Serializing to doc/js/full_list.js
[debug]: Generating asset css/style.css
[debug]: Serializing to doc/css/style.css
[debug]: Generating asset css/common.css
[debug]: Serializing to doc/css/common.css
[debug]: Generating asset css/full_list.css
[debug]: Serializing to doc/css/full_list.css
[debug]: Generating asset class_list.html
[debug]: Serializing to doc/class_list.html
[debug]: Generating asset method_list.html
[debug]: Serializing to doc/method_list.html
[debug]: Generating asset file_list.html
[debug]: Serializing to doc/file_list.html
[debug]: Generating asset frames.html
[debug]: Serializing to doc/frames.html
[debug]: Serializing to doc/_index.html
/Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:1539:in `_BlockQuote': uninitialized constant RDoc::Markup::BlockQuote (NameError)
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:470:in `apply'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:896:in `_Block'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:470:in `apply'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:856:in `_Doc'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:470:in `apply'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:834:in `_root'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:470:in `apply'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:372:in `parse'
  from /Users/saurabhnanda/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/rdoc/markdown.rb:780:in `parse'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/helpers/markup/rdoc_markdown.rb:15:in `initialize'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/helpers/html_helper.rb:85:in `new'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/helpers/html_helper.rb:85:in `html_markup_markdown'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/helpers/html_helper.rb:59:in `htmlify'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/layout/html/setup.rb:67:in `diskfile'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:363:in `render_section'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:259:in `block (2 levels) in run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:256:in `each'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:256:in `block in run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:394:in `add_options'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:255:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:277:in `block in yieldall'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:408:in `with_section'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:277:in `yieldall'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/layout/html/layout.erb:21:in `_erb_cache_5'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:287:in `erb'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/layout/html/setup.rb:62:in `layout'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:363:in `render_section'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:259:in `block (2 levels) in run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:256:in `each'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:256:in `block in run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:394:in `add_options'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:255:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:136:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/fulldoc/html/setup.rb:52:in `block in serialize_index'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/engine.rb:123:in `block in with_serializer'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/logging.rb:72:in `capture'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/engine.rb:121:in `with_serializer'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/fulldoc/html/setup.rb:51:in `serialize_index'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/fulldoc/html/setup.rb:68:in `serialize_file'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/fulldoc/html/setup.rb:11:in `block in init'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/fulldoc/html/setup.rb:10:in `each'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/fulldoc/html/setup.rb:10:in `each_with_index'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/templates/default/fulldoc/html/setup.rb:10:in `init'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:193:in `initialize'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:131:in `new'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/template.rb:136:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/templates/engine.rb:105:in `generate'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/cli/yardoc.rb:349:in `run_generate'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/cli/yardoc.rb:263:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/cli/command.rb:14:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/cli/command_parser.rb:72:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/lib/yard/cli/command_parser.rb:54:in `run'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/gems/yard-0.9.7/bin/yard:13:in `<top (required)>'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/bin/yard:23:in `load'
  from /Users/saurabhnanda/projects/vl-gitlab/vendor/bundle-danger/ruby/2.1.0/bin/yard:23:in `<main>'
```
## Expected Output

Should not crash

## Environment details:

* OS: OSX El Captian 10.11.3
* Ruby version (`bundle exec ruby -v`): ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
* YARD version (`bundle exec yard -v`): yard 0.9.7
* Relevant software dependency/versions: `rdoc = 3.12.2` although I'm not sure if it is relevant (because rdoc is not crashing when run independently).
  * [Any 3rd party libs required to reproduce, omit if none]

I have read the [Contributing Guide][contrib]. -- **YES**

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
A few notes / suggestions here:

1. The latest release of YARD is 0.9.16, I would recommend upgrading and trying that first.
2. Using `bundle exec rdoc` does not necessarily exercise the same code paths as `bundle exec yard` (i.e., YARD is using the Markdown component, which RDoc may not be), so I do believe the rdoc vesion is relevant here especially since the backtrace indicates the crash is coming directly from RDoc. That is also an old version of `rdoc`, and you may consider upgrading it as well (the latest version right now is `6.0.4`).
3. Another thing you might try doing if this is persisting is to add another Markdown provider library like `redcarpet` or `kramdown` to your Gemfile. Adding those gems and running bundle should be sufficient for YARD to use those libs instead, which it favors over RDoc's markdown library, since they are generally more performant (`redcarpet` is native code and _much_ faster than pure Ruby impls).

Hope that helps.

**Comment by saurabhnanda** [comment]
I can confirm that adding `redcarpet` in gemfile fixes the problem. Thanks for your help.
