### ISSUE TITLE
Need Better Plugin Guide

### ISSUE THREAD

**Issue by GerryG** [lsegal/yard#1201]
We have a substantial ruby/rails project that used yard for docs, and it has a DSL for extending it. I'm trying to write a plugin for yard so that it will handle our DSL declarations. I've managed to get a few things working, and I had it loading my plugin from a gem, but now I'm failing and don't know why.

The problem is that it will not load the plugin. It finds it in gems and tries to load it, but it doesn't actually find the plugin. I think it loads the gem, and probably does't find what it looks for.

## Steps to reproduce

The code is on a branch here: https://github.com/GerryG/decko/tree/yard

1. cd yard
2. gem build *.gemspec
3. (sudo) gem install yard-card-0.0.1.gem
4. cd ../card
4. yard

## Actual Output

 gem build yard-card.gemspec  ; sudo gem install yard-card-0.0.1.gem  ; cd ../card ; yard  2>&1 | tee xx.out
  Successfully built RubyGem
  Name: yard-card
  Version: 0.0.1
  File: yard-card-0.0.1.gem
Successfully installed yard-card-0.0.1
Parsing documentation for yard-card-0.0.1
Installing ri documentation for yard-card-0.0.1
Done installing documentation for yard-card after 0 seconds
1 gem installed
[error]: Error loading plugin 'yard-card'
[warn]: Error yard-card, cannot load such file -- yard-card /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/var/lib/gems/2.5.0/gems/yard-0.9.16/lib/yard/config.rb:162:in `load_plugin'
/var/lib/gems/2.5.0/gems/yard-0.9.16/lib/yard/config.rb:176:in `block in load_gem_plugins'
/usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1027:in `block in each'
/usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1026:in `each'
/usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1026:in `each'
/var/lib/gems/2.5.0/gems/yard-0.9.16/lib/yard/gem_index.rb:19:in `each'
/var/lib/gems/2.5.0/gems/yard-0.9.16/lib/yard/config.rb:173:in `load_gem_plugins'
/var/lib/gems/2.5.0/gems/yard-0.9.16/lib/yard/config.rb:147:in `load_plugins'
/var/lib/gems/2.5.0/gems/yard-0.9.16/lib/yard/config.rb:126:in `load'
/var/lib/gems/2.5.0/gems/yard-0.9.16/lib/yard.rb:69:in `<top (required)>'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/var/lib/gems/2.5.0/gems/yard-0.9.16/bin/yard:11:in `<top (required)>'
/usr/local/bin/yard:23:in `load'
/usr/local/bin/yard:23:in `<main>'
[warn]: @param tag has unknown parameter name: key 
    in file `lib/card/codename' near line 28
[warn]: in YARD::Handlers::Ruby::ClassHandler: Undocumentable superclass (class was added without superclass)
	in file 'lib/card/migration':3:

	3: class Card::Migration < ActiveRecord::Migration[4.2]

[warn]: in YARD::Handlers::Ruby::AttributeHandler: Undocumentable JOIN_OPT_KEYS
	in file 'lib/card/query/join':8:

	8: attr_accessor(*JOIN_OPT_KEYS)

[... expected output for yard without the plugin ]
The trace output is from debugging code I added near where the exception was being raised to try to narrow down what is happening.

I think the problem is that whatever the require is looking for isn't found. When I had it working, my handler wasn't called YARD::<My Class>, but when I tried to put my classes under "module YARD" it started failing. Initially I had it as "class Yard", but I fixed that and still no joy.

Is there an IRC channel or some other community site that would be better for asking questions? I'm pretty sure I'm just missing something basic, but the docs are not that much help. I wish the guides said a lot more about how to implement different things in plugins.

I can match the things I want in handlers, but the docs say very little about how you should modify or generate the needed data structures. I figured out how to change the namespace, but I really want a handler for the start of parsing on a file (is there one, I couldn't find it?). Now I have DSL method calls that need to become method definitions. I may eventually make CodeObject subclasses and custom templates so I can group them distinctly from regular methods.

## Expected Output

No error about loading yard-card, and indications in the output that my handlers are being called.

## Environment details:

* OS: Linux Mint 19
* Ruby version (`ruby -v`): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
* YARD version (`yard -v`): yard 0.9.16
* Relevant software dependency/versions:
  * [Any 3rd party libs required to reproduce, omit if none]

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
> [!NOTE]
> This is a batch message, apologies if this feels impersonal.

I am closing out a few stale issues and PRs in the YARD repo and this was flagged for automatic closure because the issue may have been fixed or is likely not planned due to the issue/PR age. If this is still an issue or you believe the issue/PR is still worth a discussion, please feel free to comment or reopen a new issue. Thanks and sorry for not getting around to this the first time!
