### ISSUE TITLE
After installing YARD 0.9.18, building yri documentation fails

### ISSUE THREAD

**Issue by mvz** [lsegal/yard#1218]
## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. (If necessary) Remove version 0.9.18: `gem uninstall yard --version 0.9.18`
2. Install version 0.9.18: `gem install yard --version 0.9.18`

## Actual Output

```
Fetching yard-0.9.18.gem
--------------------------------------------------------------------------------
As of YARD v0.9.2:

RubyGems "--document=yri,yard" hooks are now supported. You can auto-configure
YARD to automatically build the yri index for installed gems by typing:

    $ yard config --gem-install-yri

See `yard config --help` for more information on RubyGems install hooks.

You can also add the following to your .gemspec to have YARD document your gem
on install:

    spec.metadata["yard.run"] = "yri" # use "yard" to build full HTML docs.

--------------------------------------------------------------------------------
Successfully installed yard-0.9.18
Building YARD (yri) index for yard-0.9.18...
Parsing documentation for yard-0.9.18
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /home/matijs/.rbenv/versions/2.6.0/bin/ruby -c lib/yard/i18n/pot_generator.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

## Expected Output

* I expected `yri` documentation not to fail.

## Environment details:

* OS: Debian GNU/Linux, Sid.
* Ruby version (`ruby -v`): `ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]`
* YARD version (`yard -v`): `yard 0.9.18`

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by austinbutler** [comment]
Ran into the same issue on MacOS. Same versions as above. Ruby installed from Homebrew.

Trace:

```txt
Successfully installed yard-0.9.18
Exception `LoadError' at /usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- yard
Parsing documentation for yard-0.9.18
Exception `ArgumentError' at /usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser.rb:146 - invalid byte sequence in UTF-8
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:496 - undefined method `[]' for nil:NilClass
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/local/opt/ruby/bin/ruby -c lib/yard/i18n/pot_generator.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

Exception `NoMethodError' at /usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rdoc.rb:398 - undefined method `[]' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:496:in `heredoc_end?'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:473:in `get_heredoc_tk'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:346:in `get_squashed_tk'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:578:in `parse'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser/ruby.rb:180:in `initialize'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser.rb:191:in `new'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/parser.rb:191:in `for'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rdoc.rb:360:in `parse_file'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rdoc.rb:416:in `block in parse_files'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rdoc.rb:414:in `map'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rdoc.rb:414:in `parse_files'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:190:in `block in generate'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:189:in `chdir'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:189:in `generate'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:55:in `each'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:55:in `generation_hook'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/request_set.rb:323:in `block in install_hooks'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/request_set.rb:322:in `each'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/request_set.rb:322:in `install_hooks'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/request_set.rb:221:in `install'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:212:in `install_gem'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:264:in `block in install_gems'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `each'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `install_gems'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/commands/install_command.rb:165:in `execute'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/command.rb:321:in `invoke_with_build_args'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/command_manager.rb:176:in `process_args'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/command_manager.rb:146:in `run'
	/usr/local/Cellar/ruby/2.6.0_1/lib/ruby/2.6.0/rubygems/gem_runner.rb:59:in `run'
	/usr/local/opt/ruby/bin/gem:21:in `<main>'
```

Full output: https://gist.github.com/austinbutler/28e7def004bf8c218632150c19a2859f

**Comment by austinbutler** [comment]
Same issue with `0.9.17` but `0.9.16` installs successfully.

**Comment by lsegal** [comment]
This backtrace looks like a bug in RDoc parsing YARD.

**Comment by mvz** [comment]
I guess this needs to be fixed in rdoc.

**Comment by lsegal** [comment]
Thanks for following up, marking this as closed.
