### ISSUE TITLE
website sidebar broken `undefined method `menu_lists'`

### ISSUE THREAD

**Issue by falkorichter** [lsegal/yard#1255]
https://www.rubydoc.info/gems/depl/0.0.6 looks like this:
<img width="1328" alt="Screenshot 2019-06-21 at 14 46 28" src="https://user-images.githubusercontent.com/50506/59923422-abea1b00-9433-11e9-867f-6ba316064363.png">

```
undefined method `menu_lists' for #<Object:0x00007fa11a7dde68>
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/templates/default/fulldoc/html/setup.rb:108:in `menu_lists'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/templates/default/fulldoc/html/full_list.erb:24:in `_erb_cache_0'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/templates/template.rb:287:in `erb'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/templates/default/fulldoc/html/setup.rb:166:in `generate_list_contents'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/templates/default/fulldoc/html/setup.rb:152:in `generate_class_list'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/commands/list_command.rb:16:in `run'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/commands/base.rb:97:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/commands/library_command.rb:74:in `block in call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/commands/library_command.rb:91:in `call_without_fork'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/commands/library_command.rb:74:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/router.rb:159:in `route_list'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/router.rb:116:in `route'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/router.rb:56:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/bundler/gems/yard-12f56cf7d58e/lib/yard/server/rack_adapter.rb:52:in `call'
/home/app/rubydoc.info/app.rb:370:in `block in <class:DocServer>'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `block in compile!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'
/home/app/rubydoc.info/app.rb:29:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/conditionalget.rb:25:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/logger.rb:15:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/commonlogger.rb:33:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:212:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:205:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `block in call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1724:in `synchronize'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1724:in `synchronize'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/sinatra-1.4.3/lib/sinatra/base.rb:1449:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/home/app/rubydoc.info/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by lsegal** [comment]
Looked like a temporal issue with docmeta/rubydoc.info.
