### ISSUE TITLE
raise exception when parse cocoapod

### ISSUE THREAD

**Issue by SolaWing** [lsegal/yard#1308]
it's ok with ruby 2.6.4, but raise exception in ruby 2.7.0. the following is command and output:

```
0:cocoapods-1.7.5 $ yard doc --no-private
[warn]: Unknown directive @!private in file `lib/cocoapods/target.rb` near line 276
[warn]: Unknown tag @param. in file `lib/cocoapods/validator.rb` near line 41
[warn]: @param tag has unknown parameter name: capture 
    in file `lib/cocoapods/executable.rb' near line 160
[warn]: @param tag has unknown parameter name: env 
    in file `lib/cocoapods/executable.rb' near line 160
[warn]: @param tag has unknown parameter name: targets 
    in file `lib/cocoapods/command/init.rb' near line 84
[warn]: @param tag has unknown parameter name: targets 
    in file `lib/cocoapods/command/init.rb' near line 111
[warn]: Unknown tag @output in file `lib/cocoapods/command/repo/list.rb` near line 32
Traceback (most recent call last):
	26: from /Users/wang/.rbenv/versions/2.7.0/bin/yard:23:in `<main>'
	25: from /Users/wang/.rbenv/versions/2.7.0/bin/yard:23:in `load'
	24: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/bin/yard:13:in `<top (required)>'
	23: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command_parser.rb:54:in `run'
	22: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command_parser.rb:72:in `run'
	21: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command.rb:14:in `run'
	20: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/yardoc.rb:258:in `run'
	19: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/registry.rb:210:in `lock_for_writing'
	18: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/registry_store.rb:202:in `lock_for_writing'
	17: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/serializers/yardoc_serializer.rb:56:in `lock_for_writing'
	16: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/yardoc.rb:259:in `block in run'
	15: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard.rb:20:in `parse'
	14: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:113:in `parse'
	13: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/logging.rb:182:in `enter_level'
	12: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:114:in `block in parse'
	11: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:371:in `parse_in_order'
	10: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:45:in `parse'
	 9: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/logging.rb:82:in `capture'
	 8: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:46:in `block in parse'
	 7: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:442:in `parse'
	 6: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	 5: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:60:in `parse'
	 4: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:614:in `insert_comments'
	 3: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:212:in `traverse'
	 2: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:623:in `block in insert_comments'
	 1: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:274:in `line'
/Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:274:in `first': cannot get the first element of beginless range (RangeError)
```

**Comment by lsegal** [comment]
Can you print the results of `yard --debug`?

**Comment by SolaWing** [comment]
```
0:cocoapods-1.8.4 $ yard --debug
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp,rb}"] with `ruby` parser
[debug]: Parsing lib/cocoapods.rb
[debug]: Parsing lib/cocoapods/config.rb
[debug]: Parsing lib/cocoapods/target.rb
[warn]: Unknown directive @!private in file `lib/cocoapods/target.rb` near line 281
[debug]: Parsing lib/cocoapods/command.rb
[debug]: Parsing lib/cocoapods/podfile.rb
[debug]: Parsing lib/cocoapods/project.rb
[debug]: Parsing lib/cocoapods/sandbox.rb
[debug]: Parsing lib/cocoapods/open-uri.rb
[debug]: Parsing lib/cocoapods/resolver.rb
[debug]: Parsing lib/cocoapods/installer.rb
[debug]: Parsing lib/cocoapods/validator.rb
[debug]: Parsing lib/cocoapods/downloader.rb
[debug]: Parsing lib/cocoapods/executable.rb
[warn]: @param tag has unknown parameter name: capture 
    in file `lib/cocoapods/executable.rb' near line 160
[warn]: @param tag has unknown parameter name: env 
    in file `lib/cocoapods/executable.rb' near line 160
[debug]: Parsing lib/cocoapods/command/env.rb
[debug]: Parsing lib/cocoapods/command/ipc.rb
[debug]: Parsing lib/cocoapods/command/lib.rb
[debug]: Parsing lib/cocoapods/gem_version.rb
[debug]: Parsing lib/cocoapods/command/init.rb
[debug]: Parsing lib/cocoapods/command/list.rb
[debug]: Parsing lib/cocoapods/command/repo.rb
[debug]: Parsing lib/cocoapods/command/spec.rb
[debug]: Parsing lib/cocoapods/command/cache.rb
[debug]: Parsing lib/cocoapods/command/setup.rb
[debug]: Parsing lib/cocoapods/hooks_manager.rb
[debug]: Parsing lib/cocoapods/command/update.rb
[debug]: Parsing lib/cocoapods/core_overrides.rb
[debug]: Parsing lib/cocoapods/user_interface.rb
[debug]: Parsing lib/cocoapods/command/install.rb
[debug]: Parsing lib/cocoapods/installer/xcode.rb
[debug]: Parsing lib/cocoapods/sources_manager.rb
[debug]: Parsing lib/cocoapods/command/ipc/list.rb
[debug]: Parsing lib/cocoapods/command/ipc/repl.rb
[debug]: Parsing lib/cocoapods/command/ipc/spec.rb
[debug]: Parsing lib/cocoapods/command/lib/lint.rb
[debug]: Parsing lib/cocoapods/command/outdated.rb
[debug]: Parsing lib/cocoapods/command/repo/add.rb
[debug]: Parsing lib/cocoapods/command/spec/cat.rb
[debug]: Parsing lib/cocoapods/downloader/cache.rb
[debug]: Parsing lib/cocoapods/external_sources.rb
[debug]: Parsing lib/cocoapods/generator/header.rb
[debug]: Parsing lib/cocoapods/version_metadata.rb
[debug]: Parsing lib/cocoapods/command/repo/lint.rb
[debug]: Parsing lib/cocoapods/command/repo/list.rb
[warn]: Unknown tag @output in file `lib/cocoapods/command/repo/list.rb` near line 32
[debug]: Parsing lib/cocoapods/command/repo/push.rb
[debug]: Parsing lib/cocoapods/command/spec/edit.rb
[debug]: Parsing lib/cocoapods/command/spec/lint.rb
Traceback (most recent call last):
	26: from /Users/wang/.rbenv/versions/2.7.0/bin/yard:23:in `<main>'
	25: from /Users/wang/.rbenv/versions/2.7.0/bin/yard:23:in `load'
	24: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/bin/yard:13:in `<top (required)>'
	23: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command_parser.rb:54:in `run'
	22: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command_parser.rb:72:in `run'
	21: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command.rb:14:in `run'
	20: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/yardoc.rb:258:in `run'
	19: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/registry.rb:210:in `lock_for_writing'
	18: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/registry_store.rb:202:in `lock_for_writing'
	17: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/serializers/yardoc_serializer.rb:56:in `lock_for_writing'
	16: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/yardoc.rb:259:in `block in run'
	15: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard.rb:20:in `parse'
	14: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:113:in `parse'
	13: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/logging.rb:182:in `enter_level'
	12: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:114:in `block in parse'
	11: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:371:in `parse_in_order'
	10: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:45:in `parse'
	 9: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/logging.rb:82:in `capture'
	 8: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:46:in `block in parse'
	 7: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:442:in `parse'
	 6: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	 5: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:60:in `parse'
	 4: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:614:in `insert_comments'
	 3: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:212:in `traverse'
	 2: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:623:in `block in insert_comments'
	 1: from /Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:274:in `line'
/Users/wang/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:274:in `first': cannot get the first element of beginless range (RangeError)
```

**Comment by lsegal** [comment]
Looks like YARD is choking on this syntax:  https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/spec/lint.rb#L95-L99

```ruby
else
  raise Informative, if count == 1
                        "The spec did not pass validation, due to #{failure_reasons.first}."
                      else
                        "#{failure_reasons.count} out of #{count} specs failed validation."
                      end
```

We can fix this in the future but a workaround here would be to avoid this syntax and use one of the more traditional approaches, either the actual ternary operator or elsif:

```ruby
elsif count == 1
  raise Informative, "The spec did not pass validation, due to #{failure_reasons.first}."
else
  raise Informative, "#{failure_reasons.count} out of #{count} specs failed validation."
end
```

or

```ruby
else
  raise Informative, count == 1 ?
                        "The spec did not pass validation, due to #{failure_reasons.first}." :
                        "#{failure_reasons.count} out of #{count} specs failed validation."
end
```

**Comment by SolaWing** [comment]
I am not cocoapod developer，so I can’t change the code. I will use ruby2.6 instead and wait for the fix

**Comment by lsegal** [comment]
Then I would also recommend opening an issue with the cocoapods project so they can fix it as well.
