### ISSUE TITLE
Exception thrown when parsing solargraph-0.38.6

### ISSUE THREAD

**Issue by qortex** [lsegal/yard#1324]
Here is the log and the file where it fails (command is `yard gems`):
```
[warn]: @param tag has unknown parameter name: kind 
    in file `lib/solargraph/pin/base.rb' near line 29
Traceback (most recent call last):
	31: from /home/mic/.rbenv/versions/2.7.1/bin/yard:23:in `<main>'
	30: from /home/mic/.rbenv/versions/2.7.1/bin/yard:23:in `load'
	29: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/bin/yard:13:in `<top (required)>'
	28: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command_parser.rb:54:in `run'
	27: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command_parser.rb:72:in `run'
	26: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command.rb:14:in `run'
	25: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/gems.rb:21:in `run'
	24: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/gems.rb:29:in `build_gems'
	23: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/gems.rb:29:in `each'
	22: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/gems.rb:39:in `block in build_gems'
	21: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/gems.rb:39:in `chdir'
	20: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/gems.rb:41:in `block (2 levels) in build_gems'
	19: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/command.rb:14:in `run'
	18: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/yardoc.rb:258:in `run'
	17: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/registry.rb:210:in `lock_for_writing'
	16: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/registry_store.rb:202:in `lock_for_writing'
	15: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/serializers/yardoc_serializer.rb:56:in `lock_for_writing'
	14: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/cli/yardoc.rb:259:in `block in run'
	13: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard.rb:20:in `parse'
	12: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:113:in `parse'
	11: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/logging.rb:182:in `enter_level'
	10: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:114:in `block in parse'
	 9: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:371:in `parse_in_order'
	 8: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:45:in `parse'
	 7: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/logging.rb:82:in `capture'
	 6: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:46:in `block in parse'
	 5: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/source_parser.rb:442:in `parse'
	 4: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	 3: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	 2: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	 1: from /home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:445:in `on_if_mod'
/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:445:in `first': cannot get the first element of beginless range (RangeError)
```

**Comment by lsegal** [comment]
Fixed in e3e8321
