### ISSUE TITLE
Errors when run on IRB code

### ISSUE THREAD

**Issue by qortex** [lsegal/yard#1327]
Errors when running `gem install irb` with auto yard doc enabled:

```shell
$ gem install irb
Fetching irb-1.2.4.gem
Successfully installed irb-1.2.4
Building YARD (yri) index for irb-1.2.4...
[error]: Unhandled exception in YARD::Handlers::Ruby::PrivateConstantHandler:
  in `lib/irb/color.rb`:67:

	67: private_constant :TOKEN_SEQ_EXPRS

[error]: RangeError: cannot get the first element of beginless range
[error]: Stack trace:
	/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:274:in `first'
	/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:274:in `line'
	/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:623:in `block in insert_comments'
	/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ast_node.rb:212:in `traverse'
	/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:614:in `insert_comments'
	/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/yard-0.9.24/lib/yard/parser/ruby/ruby_parser.rb:60:in `parse'

Done installing documentation for irb after 0 seconds
1 gem installed
```

## Environment details:

* OS: Fedora 31
* Ruby version: ruby 2.7.1p83 with `rbenv`
* YARD version: yard 0.9.24

**Comment by lsegal** [comment]
Fixed in e3e8321
