### ISSUE TITLE
Warnings in bash script

### ISSUE THREAD

**Issue by andrykonchin** [lsegal/yard#1337]
Yard generates warnings about syntax errors in shell scripts in a project directory.

For instance for [Dynamoid](https://github.com/Dynamoid/dynamoid) project:

```shell
$ yard
[warn]: Syntax error in `bin/setup`:(2,17): syntax error, unexpected local variable or method, expecting `do' or '{' or '('
[warn]: Syntax error in `bin/stop_dynamodblocal`:(4,1): syntax error, unexpected '.'
[warn]: Syntax error in `bin/start_dynamodblocal`:(4,1): syntax error, unexpected '.'
...
Files:          38
Modules:        24 (   14 undocumented)
Classes:        26 (   16 undocumented)
Constants:      25 (   25 undocumented)
Attributes:     31 (    0 undocumented)
Methods:       229 (   67 undocumented)
 63.58% documented
```

```shell
$yard --version
yard 0.9.25
```

## Steps to reproduce

1. Clone Dynamoid repository `git clone git@github.com:Dynamoid/dynamoid.git`
2. Install Yard 0.9.25
3. Run the following command: `yard doc --debug`

## Actual Output

<details>
<summary>Click me</summary>

```shell
yard doc --debug
[debug]: Parsing ["lib/**/*.rb", "bin/*"] with `ruby` parser
[debug]: Parsing lib/dynamoid.rb
[debug]: Parsing lib/dynamoid/dirty.rb
[debug]: Parsing lib/dynamoid/tasks.rb
[debug]: Parsing lib/dynamoid/config.rb
[debug]: Parsing lib/dynamoid/errors.rb
[debug]: Parsing lib/dynamoid/fields.rb
[debug]: Parsing lib/dynamoid/adapter.rb
[debug]: Parsing lib/dynamoid/dumping.rb
[debug]: Parsing lib/dynamoid/finders.rb
[debug]: Parsing lib/dynamoid/indexes.rb
[debug]: Parsing lib/dynamoid/railtie.rb
[debug]: Parsing lib/dynamoid/version.rb
[debug]: Parsing lib/dynamoid/criteria.rb
[debug]: Parsing lib/dynamoid/document.rb
[debug]: Parsing lib/dynamoid/loadable.rb
[debug]: Parsing lib/dynamoid/undumping.rb
[debug]: Parsing lib/dynamoid/components.rb
[debug]: Parsing lib/dynamoid/persistence.rb
[debug]: Parsing lib/dynamoid/validations.rb
[debug]: Parsing lib/dynamoid/associations.rb
[debug]: Parsing lib/dynamoid/identity_map.rb
[debug]: Parsing lib/dynamoid/type_casting.rb
[debug]: Parsing lib/dynamoid/config/options.rb
[debug]: Parsing lib/dynamoid/criteria/chain.rb
[debug]: Parsing lib/dynamoid/tasks/database.rb
[debug]: Parsing lib/dynamoid/persistence/save.rb
[debug]: Parsing lib/dynamoid/dynamodb_time_zone.rb
[debug]: Parsing lib/dynamoid/persistence/import.rb
[debug]: Parsing lib/dynamoid/persistence/upsert.rb
[debug]: Parsing lib/dynamoid/associations/has_one.rb
[debug]: Parsing lib/dynamoid/application_time_zone.rb
[debug]: Parsing lib/dynamoid/associations/has_many.rb
[debug]: Parsing lib/dynamoid/associations/belongs_to.rb
[debug]: Parsing lib/dynamoid/middleware/identity_map.rb
[debug]: Parsing lib/dynamoid/associations/association.rb
[debug]: Parsing lib/dynamoid/primary_key_type_mapping.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3.rb
[debug]: Parsing lib/dynamoid/persistence/update_fields.rb
[debug]: Parsing lib/dynamoid/criteria/key_fields_detector.rb
[debug]: Parsing lib/dynamoid/associations/many_association.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/scan.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/query.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/table.rb
[debug]: Parsing lib/dynamoid/associations/single_association.rb
[debug]: Parsing lib/dynamoid/associations/has_and_belongs_to_many.rb
[debug]: Parsing lib/dynamoid/criteria/ignored_conditions_detector.rb
[debug]: Parsing lib/dynamoid/criteria/nonexistent_fields_detector.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/create_table.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/item_updater.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/batch_get_item.rb
[debug]: Parsing lib/dynamoid/criteria/overwritten_conditions_detector.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/middleware/limit.rb
[debug]: Parsing lib/dynamoid/config/backoff_strategies/constant_backoff.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/middleware/backoff.rb
[debug]: Parsing lib/dynamoid/config/backoff_strategies/exponential_backoff.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/middleware/start_key.rb
[debug]: Parsing lib/dynamoid/adapter_plugin/aws_sdk_v3/until_past_table_status.rb
[debug]: Parsing bin/setup
[warn]: Syntax error in `bin/setup`:(2,17): syntax error, unexpected local variable or method, expecting `do' or '{' or '('
[warn]: ParserSyntaxError: syntax error in `bin/setup`:(2,17): syntax error, unexpected local variable or method, expecting `do' or '{' or '('
[warn]: Stack trace:
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:601:in `on_parse_error'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:442:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:46:in `block in parse'

[debug]: Parsing bin/console
[debug]: Parsing bin/_dynamodblocal
[debug]: Parsing bin/stop_dynamodblocal
[warn]: Syntax error in `bin/stop_dynamodblocal`:(4,1): syntax error, unexpected '.'
[warn]: ParserSyntaxError: syntax error in `bin/stop_dynamodblocal`:(4,1): syntax error, unexpected '.'
[warn]: Stack trace:
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:601:in `on_parse_error'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:442:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:46:in `block in parse'

[debug]: Parsing bin/start_dynamodblocal
[warn]: Syntax error in `bin/start_dynamodblocal`:(4,1): syntax error, unexpected '.'
[warn]: ParserSyntaxError: syntax error in `bin/start_dynamodblocal`:(4,1): syntax error, unexpected '.'
[warn]: Stack trace:
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:601:in `on_parse_error'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:442:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:46:in `block in parse'

[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
[debug]: Re-generating object Dynamoid...
[debug]: Re-generating object Dynamoid::Dirty...
[debug]: Re-generating object Dynamoid::Errors...
[debug]: Re-generating object Dynamoid::Fields...
[debug]: Re-generating object Dynamoid::Fields::ClassMethods...
[debug]: Re-generating object Dynamoid::Finders...
[debug]: Re-generating object Dynamoid::Finders::ClassMethods...
[debug]: Re-generating object Dynamoid::Indexes...
[debug]: Re-generating object Dynamoid::Indexes::ClassMethods...
[debug]: Re-generating object Dynamoid::Criteria...
[debug]: Re-generating object Dynamoid::Document...
[debug]: Re-generating object Dynamoid::Document::ClassMethods...
[debug]: Re-generating object Dynamoid::Loadable...
[debug]: Re-generating object Dynamoid::Persistence...
[debug]: Re-generating object Dynamoid::Persistence::ClassMethods...
[debug]: Re-generating object Dynamoid::Validations...
[debug]: Re-generating object Dynamoid::Validations::ClassMethods...
[debug]: Re-generating object Dynamoid::Associations...
[debug]: Re-generating object Dynamoid::Associations::ClassMethods...
[debug]: Re-generating object Dynamoid::IdentityMap...
[debug]: Re-generating object Dynamoid::IdentityMap::ClassMethods...
[debug]: Re-generating object Dynamoid::Associations::ManyAssociation...
[debug]: Re-generating object Dynamoid::Associations::SingleAssociation...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::Middleware...
[debug]: Re-generating object Dynamoid::Errors::Error...
[debug]: Re-generating object Dynamoid::Errors::MissingRangeKey...
[debug]: Re-generating object Dynamoid::Errors::MissingIndex...
[debug]: Re-generating object Dynamoid::Errors::InvalidIndex...
[debug]: Re-generating object Dynamoid::Errors::RecordNotDestroyed...
[debug]: Re-generating object Dynamoid::Errors::ConditionalCheckFailedException...
[debug]: Re-generating object Dynamoid::Errors::RecordNotUnique...
[debug]: Re-generating object Dynamoid::Errors::StaleObjectError...
[debug]: Re-generating object Dynamoid::Errors::RecordNotFound...
[debug]: Re-generating object Dynamoid::Errors::DocumentNotValid...
[debug]: Re-generating object Dynamoid::Errors::InvalidQuery...
[debug]: Re-generating object Dynamoid::Errors::UnsupportedKeyType...
[debug]: Re-generating object Dynamoid::Indexes::Index...
[debug]: Re-generating object Dynamoid::Validations::ClassMethods::PresenceValidator...
[debug]: Re-generating object Dynamoid::Criteria::Chain...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::Scan...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::Query...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::Table...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::CreateTable...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::ItemUpdater...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::BatchGetItem...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::BatchGetItem::Response...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::Middleware::Limit...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::Middleware::Backoff...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::Middleware::StartKey...
[debug]: Re-generating object Dynamoid::AdapterPlugin::AwsSdkV3::UntilPastTableStatus...
[debug]: Generating asset js/jquery.js
[debug]: Serializing to doc/js/jquery.js
[debug]: Generating asset js/app.js
[debug]: Serializing to doc/js/app.js
[debug]: Generating asset js/full_list.js
[debug]: Serializing to doc/js/full_list.js
[debug]: Generating asset css/style.css
[debug]: Serializing to doc/css/style.css
[debug]: Generating asset css/common.css
[debug]: Serializing to doc/css/common.css
[debug]: Generating asset css/full_list.css
[debug]: Serializing to doc/css/full_list.css
[debug]: Generating asset class_list.html
[debug]: Serializing to doc/class_list.html
[debug]: Generating asset method_list.html
[debug]: Serializing to doc/method_list.html
[debug]: Generating asset file_list.html
[debug]: Serializing to doc/file_list.html
[debug]: Generating asset frames.html
[debug]: Serializing to doc/frames.html
[debug]: Serializing to doc/_index.html
[warn]: In file `README.md':1236: Cannot resolve link to Dynamoid::Config.namespace from text:
	...{Dynamoid::Config.namespace}...
[debug]: Serializing to doc/index.html
[warn]: In file `README.md':1236: Cannot resolve link to Dynamoid::Config.namespace from text:
	...{Dynamoid::Config.namespace}...
[debug]: Serializing to doc/file.README.html
[debug]: Serializing to doc/file.LICENSE.html
[debug]: Serializing to doc/top-level-namespace.html
[debug]: Serializing to doc/Dynamoid.html
[debug]: Serializing to doc/Dynamoid/Dirty.html
[debug]: Serializing to doc/Dynamoid/Errors.html
[debug]: Serializing to doc/Dynamoid/Fields.html
[debug]: Serializing to doc/Dynamoid/Fields/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/Finders.html
[debug]: Serializing to doc/Dynamoid/Finders/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/Indexes.html
[debug]: Serializing to doc/Dynamoid/Indexes/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/Criteria.html
[debug]: Serializing to doc/Dynamoid/Document.html
[debug]: Serializing to doc/Dynamoid/Document/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/Loadable.html
[debug]: Serializing to doc/Dynamoid/Persistence.html
[debug]: Serializing to doc/Dynamoid/Persistence/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/Validations.html
[debug]: Serializing to doc/Dynamoid/Validations/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/Associations.html
[debug]: Serializing to doc/Dynamoid/Associations/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/IdentityMap.html
[debug]: Serializing to doc/Dynamoid/IdentityMap/ClassMethods.html
[debug]: Serializing to doc/Dynamoid/Associations/ManyAssociation.html
[debug]: Serializing to doc/Dynamoid/Associations/SingleAssociation.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/Middleware.html
[debug]: Serializing to doc/Dynamoid/Errors/Error.html
[debug]: Serializing to doc/Dynamoid/Errors/MissingRangeKey.html
[debug]: Serializing to doc/Dynamoid/Errors/MissingIndex.html
[debug]: Serializing to doc/Dynamoid/Errors/InvalidIndex.html
[debug]: Serializing to doc/Dynamoid/Errors/RecordNotDestroyed.html
[debug]: Serializing to doc/Dynamoid/Errors/ConditionalCheckFailedException.html
[debug]: Serializing to doc/Dynamoid/Errors/RecordNotUnique.html
[debug]: Serializing to doc/Dynamoid/Errors/StaleObjectError.html
[debug]: Serializing to doc/Dynamoid/Errors/RecordNotFound.html
[debug]: Serializing to doc/Dynamoid/Errors/DocumentNotValid.html
[debug]: Serializing to doc/Dynamoid/Errors/InvalidQuery.html
[debug]: Serializing to doc/Dynamoid/Errors/UnsupportedKeyType.html
[debug]: Serializing to doc/Dynamoid/Indexes/Index.html
[debug]: Serializing to doc/Dynamoid/Validations/ClassMethods/PresenceValidator.html
[debug]: Serializing to doc/Dynamoid/Criteria/Chain.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/Scan.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/Query.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/Table.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/CreateTable.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/ItemUpdater.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/BatchGetItem.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/BatchGetItem/Response.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/Middleware/Limit.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/Middleware/Backoff.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/Middleware/StartKey.html
[debug]: Serializing to doc/Dynamoid/AdapterPlugin/AwsSdkV3/UntilPastTableStatus.html
Files:          38
Modules:        24 (   14 undocumented)
Classes:        26 (   16 undocumented)
Constants:      25 (   25 undocumented)
Attributes:     31 (    0 undocumented)
Methods:       229 (   67 undocumented)
 63.58% documented
```

</details>

## Expected Output

Output without messages like

```shell
[debug]: Parsing bin/setup
[warn]: Syntax error in `bin/setup`:(2,17): syntax error, unexpected local variable or method, expecting `do' or '{' or '('
[warn]: ParserSyntaxError: syntax error in `bin/setup`:(2,17): syntax error, unexpected local variable or method, expecting `do' or '{' or '('
[warn]: Stack trace:
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:601:in `on_parse_error'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:56:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:442:in `parse'
	/Users/andrykonchin/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib/yard/parser/source_parser.rb:46:in `block in parse'
```

## Environment details:

- OS: MacOS 10.14.5
- Ruby version (`ruby -v`): ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
- YARD version (`yard -v`): yard 0.9.25

- [x] I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

**Comment by lsegal** [comment]
Dynamoid has a `.document` file that specifies to parse `bin/*` as Ruby source:

https://github.com/Dynamoid/dynamoid/blob/master/.document#L2

That's likely where the warnings are coming from.

**Comment by andrykonchin** [comment]
Oh, well. Thank you 🙇 .
