### ISSUE TITLE
Running `yard` results in circular argument reference error

### ISSUE THREAD

**Issue by keithrbennett** [lsegal/yard#1413]
I am trying to run `yard server` but get this error:

```
> yard --debug server
[debug]: Attempting to access unregistered key locale on YARD::CLI::YardocOptions
[debug]: Attempting to access unregistered key locale on YARD::CLI::YardocOptions
[debug]: Parsing ["server"] with `ruby` parser
[debug]: Serializing to .yardoc/objects/root.dat
[debug]: Re-generating object ...
<internal:/Users/keith.bennett/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/templates/template.rb:320: circular argument reference - section (SyntaxError)
	from <internal:/Users/keith.bennett/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/templates/engine.rb:36:in `template'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/templates/engine.rb:104:in `generate'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/cli/yardoc.rb:335:in `run_generate'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/cli/yardoc.rb:249:in `run'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/cli/command.rb:13:in `run'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/cli/command_parser.rb:71:in `run'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/lib/yard/cli/command_parser.rb:53:in `run'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/gems/yard-0.8.7.4/bin/yard:12:in `<top (required)>'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/bin/yard:25:in `load'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/bin/yard:25:in `<main>'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `eval'
	from /Users/keith.bennett/.rvm/gems/ruby-3.0.3/bin/ruby_executable_hooks:22:in `<main>'
```

The error also occurs with `yard doc`.

## Environment details:

- OS: Mac OS 11.6.1 (Big Sur)
- Ruby version: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20] (also tested on 2.7.4)
- YARD version: yard 0.8.7.4

**Comment by lsegal** [comment]
This is a very old version of YARD. Can you reproduce this on the latest release?

**Comment by keithrbennett** [comment]
My apologies. My gem server was pointed to an internal gem server that was not up to date. I've tried it with the current version and do not have the problem. I will close this issue now.
