### ISSUE TITLE
Error starting server: nil port

### ISSUE THREAD

**Issue by ximes** [lsegal/yard#1493]
I'm failing to start the Yard server recently. There's apparently an issue with the port parameter which is not passed correctly to Puma.

## Steps to reproduce

1. Run the following command: `yard server` or even `yard server -p 8808`

## Actual Output

It errors with the following:

```
>> YARD 0.9.32 documentation server at http://localhost:8808
~/gems/puma-6.2.1/lib/puma/dsl.rb:314:in `Integer': can't convert nil into Integer (TypeError)

      bind URI::Generic.build(scheme: 'tcp', host: host, port: Integer(port)).to_s
                                                                       ^^^^
        from ~/gems/puma-6.2.1/lib/puma/dsl.rb:314:in `port'
        from config/puma.rb:4:in `_load_from'
```

## Expected Output

The server starts correctly instead. 
If I provide a ENV var for it, as in the following command:

```
PORT=8808 yard server
```
server opens just fine.

## Environment details:

- OS: Ubuntu 22.04.2 LTS
- Ruby version (`ruby -v`): ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [x86_64-linux]
- YARD version (`yard -v`): yard 0.9.32
- Relevant software dependency/versions:
  - Puma version: 6.2.1

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

**Comment by ximes** [comment]
Argh you're right. I had a local port override in my `config/puma.rb` (`port ENV["PORT"]`) which I missed, All working fine here :) My bad, closing it.
