### ISSUE TITLE
ArgumentError: NilClass is not a valid CodeObject whilst installing RMagick Gem

### ISSUE THREAD

**Issue by jbergler** [lsegal/yard#826]
```bash
$ yardoc -v
yard 0.8.7.6

$ gem install --user-install rmagick -v 2.13.2
Fetching: rmagick-2.13.2.gem (100%)
WARNING:  You don't have /home/jbergler/.gem/ruby/1.9.3/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
Successfully installed rmagick-2.13.2
1 gem installed
Installing ri documentation for rmagick-2.13.2...
Building YARD (yri) index for rmagick-2.13.2...
[error]: Unhandled exception in YARD::Handlers::C::MixinHandler:
[error]:   in `ext/RMagick/rmmain.c`:611:

	611: rb_include_module(Class_Pixel, observable);

[error]: ArgumentError: NilClass is not a valid CodeObject
[error]: Stack trace:
	/usr/lib/ruby/gems/1.9.3/gems/yard-0.8.7.6/lib/yard/code_objects/base.rb:23:in `push'
	/usr/lib/ruby/gems/1.9.3/gems/yard-0.8.7.6/lib/yard/handlers/c/mixin_handler.rb:10:in `block (2 levels) in <class:MixinHandler>'
	/usr/lib/ruby/gems/1.9.3/gems/yard-0.8.7.6/lib/yard/handlers/c/mixin_handler.rb:7:in `scan'
	/usr/lib/ruby/gems/1.9.3/gems/yard-0.8.7.6/lib/yard/handlers/c/mixin_handler.rb:7:in `block in <class:MixinHandler>'
	/usr/lib/ruby/gems/1.9.3/gems/yard-0.8.7.6/lib/yard/handlers/processor.rb:114:in `block (2 levels) in process'
	/usr/lib/ruby/gems/1.9.3/gems/yard-0.8.7.6/lib/yard/handlers/processor.rb:112:in `each'

Installing RDoc documentation for rmagick-2.13.2...
````

**Comment by lsegal** [comment]
Sorry for taking so long. This is now resolved, but the error is still a warning, since the `observable` variable syntax used is not detectable by YARD (it does not yet support const lookups to resolve variables). A workaround would be to use something like the variable name `rb_cObservable` to hint to YARD what the actual class name is.
