### ISSUE TITLE
ruby_parser_spec.rb fails in ruby 2.2.0 

### ISSUE THREAD

**Issue by ChrisLundquist** [lsegal/yard#861]
```
# Added debug puts statement
$ git diff
```
```diff
diff --git a/lib/yard/parser/ruby/ruby_parser.rb b/lib/yard/parser/ruby/ruby_parser.rb
index a790391..9fb7390 100644
--- a/lib/yard/parser/ruby/ruby_parser.rb
+++ b/lib/yard/parser/ruby/ruby_parser.rb
@@ -451,6 +451,7 @@ module YARD
         end
 
         def on_params(*args)
+          puts args.inspect
           args.map! do |arg|
             next arg unless arg.class == Array
 ```
```
# Run the tests in different versions of ruby
$ rbenv shell 2.2.0
$ bundle exec rspec > 2.2.0.txt
$ rbenv shell 2.1.3
$ bundle exec rspec > 2.1.3.txt
$ diff *.txt
```

```diff
272,274c272,274
< .[[s(:ident, "one")], nil, nil, nil, [[s(:label, "two"), s(:int, "2")], [s(:label, "three"), s(:int, "3")]], nil, nil]
< .[[s(:ident, "one")], nil, nil, nil, [[s(:label, "two"), false], [s(:label, "three"), false]], nil, nil]
< .[[s(:ident, "one")], nil, nil, nil, nil, s(:ident, "two"), nil]
---
> .[[s(:ident, "one")], nil, nil, nil, [[98104, s(:int, "2")], [98112, s(:int, "3")]], nil, nil]
> F[[s(:ident, "one")], nil, nil, nil, [[98104, false], [98112, false]], nil, nil]
> F[[s(:ident, "one")], nil, nil, nil, nil, s(:ident, "two"), nil]
295,297c295,297
< .[[s(:ident, "a")], [[s(:ident, "b"), s(:int, "1")]], s(:rest_param, s(:ident, "c")), [s(:ident, "d")], [[s(:label, "e"), s(:int, "3")]], s(:ident, "f"), s(:blockarg, s(:ident, "g"))]
< .[[s(:ident, "a")], [[s(:ident, "b"), s(:int, "1")]], s(:rest_param, s(:ident, "c")), [s(:ident, "d")], [[s(:label, "e"), s(:int, "3")], [s(:label, "f"), false]], s(:ident, "g"), s(:blockarg, s(:ident, "h"))]
< .[nil, nil, nil, nil, nil, nil, nil]
---
> .[[s(:ident, "a")], [[s(:ident, "b"), s(:int, "1")]], s(:rest_param, s(:ident, "c")), [s(:ident, "d")], [[15824, s(:int, "3")]], s(:ident, "f"), s(:blockarg, s(:ident, "g"))]
> F[[s(:ident, "a")], [[s(:ident, "b"), s(:int, "1")]], s(:rest_param, s(:ident, "c")), [s(:ident, "d")], [[15824, s(:int, "3")], [15512, false]], s(:ident, "g"), s(:blockarg, s(:ident, "h"))]
> F[nil, nil, nil, nil, nil, nil, nil]
451,452c451,525
< Finished in 5.57 seconds
< 1682 examples, 0 failures
---
> Failures:
> 
>   1) YARD::Parser::Ruby::RubyParser#parse should handle defs with named arguments with default values
>      Failure/Error: YARD::Parser::Ruby::RubyParser.new(stmt, nil).parse.root.first
>      NoMethodError:
>        undefined method `type' for 98104:Fixnum
>      # ./lib/yard/parser/ruby/ruby_parser.rb:461:in `block (2 levels) in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `block in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
>      # ./spec/parser/ruby/ruby_parser_spec.rb:5:in `stmt'
>      # ./spec/parser/ruby/ruby_parser_spec.rb:193:in `block (3 levels) in <top (required)>'
> 
>   2) YARD::Parser::Ruby::RubyParser#parse should handle defs with named arguments without default values
>      Failure/Error: YARD::Parser::Ruby::RubyParser.new(stmt, nil).parse.root.first
>      NoMethodError:
>        undefined method `type' for 98104:Fixnum
>      # ./lib/yard/parser/ruby/ruby_parser.rb:461:in `block (2 levels) in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `block in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
>      # ./spec/parser/ruby/ruby_parser_spec.rb:5:in `stmt'
>      # ./spec/parser/ruby/ruby_parser_spec.rb:200:in `block (3 levels) in <top (required)>'
> 
>   3) YARD::Parser::SourceParser#parse_statements supports named arguments with default values
>      Failure/Error: YARD.parse_string 'def foo(a, b = 1, *c, d, e: 3, **f, &g) end'
>      NoMethodError:
>        undefined method `type' for 15824:Fixnum
>      # ./lib/yard/parser/ruby/ruby_parser.rb:461:in `block (2 levels) in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `block in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
>      # ./lib/yard/parser/source_parser.rb:439:in `parse'
>      # ./lib/yard/parser/source_parser.rb:117:in `parse_string'
>      # ./lib/yard.rb:25:in `parse_string'
>      # ./spec/parser/source_parser_spec.rb:713:in `block (3 levels) in <top (required)>'
> 
>   4) YARD::Parser::SourceParser#parse_statements supports named arguments without default values
>      Failure/Error: YARD.parse_string 'def foo(a, b = 1, *c, d, e: 3, f:, **g, &h) end'
>      NoMethodError:
>        undefined method `type' for 15824:Fixnum
>      # ./lib/yard/parser/ruby/ruby_parser.rb:461:in `block (2 levels) in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:459:in `block in on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `map!'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:455:in `on_params'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
>      # ./lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
>      # ./lib/yard/parser/source_parser.rb:439:in `parse'
>      # ./lib/yard/parser/source_parser.rb:117:in `parse_string'
>      # ./lib/yard.rb:25:in `parse_string'
>      # ./spec/parser/source_parser_spec.rb:721:in `block (3 levels) in <top (required)>'
> 
> Finished in 5.89 seconds
> 1682 examples, 4 failures
> 
> Failed examples:
> 
> rspec ./spec/parser/ruby/ruby_parser_spec.rb:192 # YARD::Parser::Ruby::RubyParser#parse should handle defs with named arguments with default values
> rspec ./spec/parser/ruby/ruby_parser_spec.rb:199 # YARD::Parser::Ruby::RubyParser#parse should handle defs with named arguments without default values
> rspec ./spec/parser/source_parser_spec.rb:712 # YARD::Parser::SourceParser#parse_statements supports named arguments with default values
> rspec ./spec/parser/source_parser_spec.rb:720 # YARD::Parser::SourceParser#parse_statements supports named arguments without default values
```

**Comment by lsegal** [comment]
This is a bug in Ruby 2.2.0p0 see #825
