### ISSUE TITLE
Documenting private constants fails when `private_constant` argument is not a symbol

### ISSUE THREAD

**Issue by backus** [lsegal/yard#902]
Here are a few examples

```sh
$ cat example1.rb
class Foo
  BAR, BAZ, BUX = 1, 2, 3

  # constants(false) # => [:BAR, :BAZ, :BUX]
  private_constant(*constants(false))
end
$ cat example2.rb
class Foo
  BAR = 1

  def self.private_constant_symbol
    :BAR
  end

  private_constant(private_constant_symbol)
end
$ cat example3.rb
class Foo
  BAR = 1

  @constant_name = :BAR

  private_constant(@constant_name)
end
$ yardoc example1.rb
[error]: Unhandled exception in YARD::Handlers::Ruby::PrivateConstantHandler:
[error]:   in `example1.rb`:5:

	5: private_constant(*constants(false))

[error]: NameError: uninitialized constant YARD::Handlers::Ruby::PrivateConstantHandler::NamespaceMissingError
[error]: Stack trace:
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:33:in `rescue in privatize_constant'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:25:in `privatize_constant'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:11:in `block (2 levels) in <class:PrivateConstantHandler>'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:8:in `each'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:8:in `block in <class:PrivateConstantHandler>'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/processor.rb:114:in `block (2 levels) in process'

Files:           1
Modules:         0 (    0 undocumented)
Classes:         1 (    1 undocumented)
Constants:       0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 0.00% documented
$ yardoc example2.rb
[error]: Unhandled exception in YARD::Handlers::Ruby::PrivateConstantHandler:
[error]:   in `example2.rb`:8:

	8: private_constant(private_constant_symbol)

[error]: NameError: uninitialized constant YARD::Handlers::Ruby::PrivateConstantHandler::NamespaceMissingError
[error]: Stack trace:
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:33:in `rescue in privatize_constant'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:25:in `privatize_constant'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:11:in `block (2 levels) in <class:PrivateConstantHandler>'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:8:in `each'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:8:in `block in <class:PrivateConstantHandler>'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/processor.rb:114:in `block (2 levels) in process'

/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/rdoc-4.1.1/lib/rdoc/rdoc.rb:35: warning: already initialized constant RDoc::RDoc::GENERATORS
/Users/johnbackus/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rdoc/rdoc.rb:35: warning: previous definition of GENERATORS was here
Files:           1
Modules:         0 (    0 undocumented)
Classes:         1 (    1 undocumented)
Constants:       1 (    1 undocumented)
Methods:         1 (    1 undocumented)
 0.00% documented
$ yardoc example3.rb
[error]: Unhandled exception in YARD::Handlers::Ruby::PrivateConstantHandler:
[error]:   in `example3.rb`:6:

	6: private_constant(@constant_name)

[error]: NameError: uninitialized constant YARD::Handlers::Ruby::PrivateConstantHandler::NamespaceMissingError
[error]: Stack trace:
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:33:in `rescue in privatize_constant'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:25:in `privatize_constant'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:11:in `block (2 levels) in <class:PrivateConstantHandler>'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:8:in `each'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/ruby/private_constant_handler.rb:8:in `block in <class:PrivateConstantHandler>'
	/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/yard-0.8.7.6/lib/yard/handlers/processor.rb:114:in `block (2 levels) in process'

Files:           1
Modules:         0 (    0 undocumented)
Classes:         1 (    1 undocumented)
Constants:       1 (    1 undocumented)
Methods:         0 (    0 undocumented)
 0.00% documented
```

example1 is the usage I am using that I wish worked.  Here are a few examples of this use of `private_constant` in the wild if you are curious:

* https://github.com/mbj/anima/blob/master/lib/anima/error.rb#L7
* https://github.com/dkubb/yardstick/pull/34#discussion-diff-41093033

**Comment by lsegal** [comment]
There are no plans to support any of those declaration formats in YARD.

Quite simply, YARD can't parse any of these lines statically-- it depends on dynamic interpretation of your program which YARD does not do.

That said, the error is interesting, that looks like a bug. You *should* be getting an [UndocumentableError](http://www.rubydoc.info/gems/yard/YARD/Parser/UndocumentableError) letting you know of the unsupported nature of the declaration. That should be fixed.

**Comment by lsegal** [comment]
Accidentally closed... once the exception is fixed, this will be closed as WontFix, though.

**Comment by lsegal** [comment]
The name error issue should now be resolved.

**Comment by backus** [comment]
Thanks for the quick response
