### ISSUE TITLE
tests fail on Ruby 2.3?

### ISSUE THREAD

**Issue by wwood** [lsegal/yard#927]
Hey, we are in the process of updating Ruby for the GNU Guix package manager, and it seems the specs no longer pass. Running this outside Guix with rvm,
```
$ rake
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[Module, Object, ERB::Util, YARD::Templates, YARD::Server::Commands, YARD::Server, YARD::Parser::Ruby::Legacy::RubyToken, YARD::Parser::Ruby, PP::ObjectMixin, YARD::Parser::Ruby::Legacy, YARD::Parser, YARD::Handlers, YARD::CodeObjects, YARD, Kernel, BasicObject]
.............................................

Failures:

  1) YARD::Parser::Ruby::RubyParser#parse finds lone comments
     Failure/Error: expect(comment.type).to eq :comment
     
       expected: :comment
            got: :void_stmt
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -:comment
       +:void_stmt
       
     # ./spec/parser/ruby/ruby_parser_spec.rb:355:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:134:in `block (2 levels) in <top (required)>'

Finished in 6.62 seconds (files took 0.82493 seconds to load)
1686 examples, 1 failure

Failed examples:

rspec ./spec/parser/ruby/ruby_parser_spec.rb:341 # YARD::Parser::Ruby::RubyParser#parse finds lone comments
```
Any ideas? Sorry..
Thanks.

**Comment by lsegal** [comment]
Could just be a brittle test. Not sure if this affects actual functionality.

**Comment by wwood** [comment]
Possibly, though the test passes on 2.3.4. I'll let you be the judge of that.

**Comment by lsegal** [comment]
Closing since this works with the latest Ruby.

**Comment by wwood** [comment]
Sorry, my mistake. I think I meant Ruby 2.**2**.4 not 2.3.4, since there is only 2.3.0 is the latest. So the test fails on the newest version of Ruby, and the issue should be re-opened?

**Comment by lsegal** [comment]
Thanks, sorry about the confusion!

**Comment by wwood** [comment]
The confusion was all on me. Thanks for the fix.
