### ISSUE TITLE
Deprecation warning with rake 11: 'last_comment` is deprecated, use 'last_description` instead

### ISSUE THREAD

**Issue by wojtha** [lsegal/yard#966]
```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
```

After changing `warn`to `raise` at `rake-11.1.2/lib/rake/task_manager.rb:10` I got:

```
RuntimeError: [DEPRECATION] `last_comment=` is deprecated.  Please use `last_description=` instead.
  /home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/task_manager.rb:10:in `last_comment'
  /home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:69:in `define'
  /home/wojtha/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:61:in `initialize'
  /home/wojtha/Code/inm/portal/Rakefile:10:in `new'
  /home/wojtha/Code/inm/portal/Rakefile:10:in `<top (required)>'
```

**Comment by lsegal** [comment]
Already fixed in master, see #946
