### ISSUE TITLE
`yard server` unknown server start error

### ISSUE THREAD

**Issue by LynnCo** [lsegal/yard#988]
First off, apologies for the lack of detail, as I really can't make heads or tails of the traceback, which is the whole point of this issue.

---

I'm trying to setup a local yard server for [this project](https://github.com/collectqt/theblockbot). The documentation is a mess of formatting styles (like the use of hash rocket [here](https://github.com/CollectQT/theblockbot/blob/3f9051333408edfb98efaf45c07b39c4569f52e4/lib/meta_twitter.rb#L35)) so I expected that yard server would fail to run. I just don't get any indication from the `yard server` traceback of -why- the code isn't running.

I can successfully run `yard server`(that is, I can see output like that on rdoc.info at <http://localhost:PORT>) on a project I created with `rails new`, so I know its something to do with my project. So here's a snippet of the traceback I get

```
YARD 0.9.1 documentation server at http://localhost:1111
[8071] Puma starting in cluster mode...
[8071] * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
[8071] * Min threads: 5, max threads: 5
[8071] * Environment: development
[8071] * Process workers: 2
[8071] * Preloading application
[8071] * Listening on tcp://0.0.0.0:1111
[8071] Use Ctrl-C to stop
config/puma.rb:14:in `block in _load_from': uninitialized constant #<Class:#<Puma::DSL:0x007fa3645ef4e8>>::ActiveRecord (NameError)
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:269:in `block in run_hooks'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:269:in `each'
config/puma.rb:14:in `block in _load_from'	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:269:in `run_hooks'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:237:in `worker'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `fork'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `times'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `spawn_workers'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:424:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/rack/handler/puma.rb:51:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/server/rack_adapter.rb:65:in `start'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/server.rb:49:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/command.rb:13:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/command_parser.rb:71:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/command_parser.rb:53:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/bin/yard:12:in `<top (required)>'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/yard:23:in `load'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/yard:23:in `<main>'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
: uninitialized constant #<Class:#<Puma::DSL:0x007fa3645ef4e8>>::ActiveRecord (NameError)
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:269:in `block in run_hooks'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:269:in `each'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:269:in `run_hooks'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:237:in `worker'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block (2 levels) in spawn_workers'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `fork'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:120:in `block in spawn_workers'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `times'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:116:in `spawn_workers'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cluster.rb:424:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/rack/handler/puma.rb:51:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/server/rack_adapter.rb:65:in `start'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/server.rb:49:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/command.rb:13:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/command_parser.rb:71:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/lib/yard/cli/command_parser.rb:53:in `run'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/gems/yard-0.9.1/bin/yard:12:in `<top (required)>'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/yard:23:in `load'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/yard:23:in `<main>'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/cyrin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

(after this point the output repeats infinitely)

My environment:
* OSX 10.11.5
* Ruby 2.3.1
* Yard 0.9.1

My expected result is that instead of the backtrace above, I get an error message about where it is in my project that is causing yard to have errors. I'm 100% willing to work out a pull request to resolve this issue :+1:

**Comment by lsegal** [comment]
The backtrace is coming from puma directly. It looks like puma is finding the `config/puma.rb` file in the root of the project and executing it, which certainly won't work, and definitely not what you want to do (it spawns a database, brings up rails, etc). This is default puma behavior, and I'm not sure you can turn it off, so I would suggest not using puma with `yard server`.

If puma is the only Rack adapter you have installed, you may consider running `gem install thin` or simply using webrick instead of Rack with `yard server -s webrick`.

I'm marking this as closed because this is specific to puma and there's nothing YARD can do about this. Puma has [no adapter option to disable reading of the config file on boot](https://github.com/puma/puma/blob/master/lib/rack/handler/puma.rb). This is something you may want to suggest as a feature to that project.

**Comment by maxcal** [comment]
@lsegal is it possible to specify which server to use in the YARD config so that you don't have to run it with `-s webrick` every time?
