### ISSUE TITLE
lib/yard/parser/ruby/ruby_parser.rb error, parsing ruby/ruby/lib/csv.rb

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#993]
Problem occurred with 0.9.3.  I was re-generating files of the Ruby Core & Std-Lib, they have parsed fine with 0.9.0 and maybe 0.9.1.  From debug output, sstart and lstart are nil.

Only one file being parsed - [ruby/ruby/lib/csv.rb](https://github.com/ruby/ruby/blob/trunk/lib/csv.rb)

Following is error info:

Note: Added the following line at [yard/lib/yard/parser/ruby/ruby_parser.rb](https://github.com/lsegal/yard/blob/master/lib/yard/parser/ruby/ruby_parser.rb) : 228

```ruby
puts "visit_event  #{node.type.to_s.ljust(15)}  #{sstart ? sstart.to_s.rjust(6) : '   nil'}    #{@ns_charno - 1}      #{lstart ? lstart.to_s.rjust(6) : '   nil'}    #{lineno}"
```

Generated the following output:

```
             node.type        sstart  @ns_charno    lstart  lineno
                                         - 1
visit_event  arg_paren         59123    59127        1526    1526
visit_event  symbol            59180    59197        1527    1527
visit_event  arg_paren         59179    59198        1527    1527
visit_event  arg_paren         59319    59328        1530    1530
visit_event  else              59301    59353        1530    1531
visit_event  when              59256    59353        1529    1531
visit_event  case              59221    59353        1528    1531
visit_event  if                  nil    59376         nil    1532
[warn]: Cannot parse `lib/csv.rb': bad value for range
[warn]: ArgumentError: bad value for range
[warn]: Stack trace:
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.2/lib/yard/parser/ruby/ruby_parser.rb:229:in `initialize'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.2/lib/yard/parser/ruby/ruby_parser.rb:229:in `new'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.2/lib/yard/parser/ruby/ruby_parser.rb:229:in `visit_event'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.2/lib/yard/parser/ruby/ruby_parser.rb:160:in `on_if'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.2/lib/yard/parser/ruby/ruby_parser.rb:53:in `parse'
        C:/Ruby23/lib/ruby/gems/2.3.0/gems/yard-0.9.2/lib/yard/parser/ruby/ruby_parser.rb:53:in `parse'
```

**Comment by lsegal** [comment]
Thanks for reporting, fixed and tagged!
